### ISSUE TITLE
피드백

### ISSUE THREAD

**Issue by dbgusrb12** [chae-lyn/java-study-lyn#1]
- [2차원 배열](https://github.com/chae-lyn/java-study-lyn/tree/study/3.Array#2%EC%B0%A8%EC%9B%90-%EB%B0%B0%EC%97%B4)

  오타났다 (존대 => 존재)

- [부호 연산자](https://github.com/chae-lyn/java-study-lyn/tree/study/4.Operator#%EB%B6%80%ED%98%B8-%EC%97%B0%EC%82%B0%EC%9E%90--)

  ```java
  int x = 10;
  int y = +x;     // y = -10     <= (????) 다시 확인해봐
  ```

- [쉬프트 연산자](https://github.com/chae-lyn/java-study-lyn/tree/study/4.Operator#%EC%89%AC%ED%94%84%ED%8A%B8-%EC%97%B0%EC%82%B0%EC%9E%90--)

  비트의 자리를 이동 시키는거야 채린아. 비트를 직접 다루는 연산자는 명시하는게 좋을듯.

- [비트 연산자](https://github.com/chae-lyn/java-study-lyn/tree/study/4.Operator#%EB%B9%84%ED%8A%B8-%EC%97%B0%EC%82%B0%EC%9E%90--)

  이거도 마찬가지 두 피연산자를 비트로 바꿔서 각 자릿수를 비교하는거야. 설명이 너무 막연해서 헷갈릴거 같아.

**Comment by chae-lyn** [comment]
쉬프트, 비트 연산자는 아직 개념이 확실히 잡히지 않아서 추후 더 수정하겠습니다 센세 😥

**Comment by chae-lyn** [comment]
피드백 수정완료!

**Comment by dbgusrb12** [comment]
이슈 종료
